CREATE TABLE [dbo].[Orders] (
    [Orders Id]                           INT          NOT NULL,
	[Customers Id]                           INT          NOT NULL,
    [First name]                   CHAR (10)    NOT NULL,
    [Last name]                    CHAR (20)    NOT NULL,
    [Company]                      CHAR (20)    NULL,
    [Address Line 1]               CHAR (20)    NOT NULL,
    [Address Line 2]               CHAR (20)    NULL,
    [City]                         CHAR (20)    NOT NULL,
    [Postcode]                     INT          NOT NULL,
    [Country]                      CHAR (10)    NOT NULL,
    [State]                        CHAR (10)    NULL,
    [First name Shipping]          CHAR (10)    NULL,
    [Last name Shipping]           CHAR (20)    NULL,
    [Company Shipping]             CHAR (20)    NULL,
    [Address Line 1 Shipping]      CHAR (20)    NULL,
    [Address Line 2 Shipping]      CHAR (20)    NULL,
    [City Shipping]                CHAR (20)    NULL,
    [Postcode Shipping]            INT          NULL,
    [Country Shipping]             CHAR (10)    NULL,
    [State Shipping]               CHAR (10)    NULL,
    [E-mail]                       VARCHAR (25) NOT NULL,
    [Phone]                        INT          NOT NULL,
    [Payment Method]               CHAR (10)    NOT NULL,
    [Transaction ID]               INT          NOT NULL,
    [Customer note]                VARCHAR (50) NULL,
    [Date Created]                 CHAR (20)    NOT NULL,
    [Status]                       CHAR (10)    NOT NULL,
    [Customer IP]                  CHAR (10)    NULL,
    [Vehicle Name]                 CHAR (10)    NOT NULL,
    [Pickup Location]              CHAR (10)    NOT NULL,
    [Dropoff Location]             CHAR (10)    NOT NULL,
    [Pickup Date]                  DATETIME     NOT NULL,
    [Dropoff Date]                 DATETIME     NOT NULL,
    [Vehicle ID]                   SMALLINT     NOT NULL,
    [Driver Age]                   BIT          NOT NULL,
    [Total time]                   TINYINT      NOT NULL,
    [Price Amount]                 NCHAR (10)   NOT NULL,
    [Desposit Amount]              NCHAR (10)   NOT NULL,
    [Insurance Amount]             NCHAR (10)   NOT NULL,
    [Remaining Amount]             NCHAR (10)   NOT NULL,
    [Quantity]                     TINYINT      NOT NULL,
    [Order SubTotal Price]         NCHAR (10)   NOT NULL,
    [Order Total Price]            NCHAR (10)   NOT NULL,
    [Order Total Desposit Amount]  NCHAR (10)   NOT NULL,
    [Order Total Insurance Amount] NCHAR (10)   NOT NULL,
    [Order Total Remaining Amount] NCHAR (10)   NOT NULL,
    PRIMARY KEY CLUSTERED ([Orders Id] ASC),
    CONSTRAINT [Vehicle ID] FOREIGN KEY ([Vehicle ID]) REFERENCES [dbo].[Fleet] ([Vehicle ID]), 
    CONSTRAINT [Customers Id] FOREIGN KEY ([Customers Id]) REFERENCES [Customers]([Customers Id])
);